### ISSUE TITLE
Allow productions to be 'deleted' by a certain version

### ISSUE THREAD

**Issue by AntonyBlakey** [NomicFoundation/slang#182]
Allows for empty versions of productions
Correctly guards production use according to the applicable versions

**Comment by OmarTawfik** [comment]
@AntonyBlakey found one case of this. The form:

```solidity
    function () external payable
    {
    }
```

Without a function name was legal before `0.6.0` to indicate a fallback function. It is illegal afterwards.

**Comment by OmarTawfik** [comment]
Suggestion: perhaps make `versioned` map values an `Option<Expression>` instead of just `Expression`:

```yml
versioned:
  0.4.0:
    reference: "foo" # legal here
  0.5.0: null # disallowed here
  0.6.0:
     reference: "bar" # look who is back!
```
