### ISSUE TITLE
Token fragment names are dropped from parser codegen

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#242]
Given our current grammar for comments:

```yaml
- name: MultilineComment
  kind: Token
  delimitedBy:
    open: /*
    config: { name: content }
    zeroOrMore:
      choice:
        - not:
            terminal: "*"
        - sequence:
            - terminal: "*"
            - not:
                terminal: /
    close: "*/"
```

And using this input:

```solidity
/* foo */
```

Running the current parser:

```bash
solidity_rust_cli input.sol --version "0.8.0" --yaml -
```

Currently produces:

```yaml!
Rule
kind: SourceUnit
children:
- !Rule
  kind: LeadingTrivia
  children:
  - !Token
    kind: MultilineComment
    lex_node: !Chars
      start: 0
      end: 9
```

No `content` node exists at all. I also looked at the generated code, and I don't see a `content` kind anywhere. Perhaps we are missing a `FragmentKind` enum for such cases? I see it was added in #92
