### ISSUE TITLE
Parser returns incorrect ranges for graphic characters

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#253]
Taking this [input file](https://raw.githubusercontent.com/tintinweb/smart-contract-sanctuary-arbitrum/c31da2cc5e68591b204038c684140ca31658a1e7/contracts/mainnet/10/10ecbe39b914bdb43850932eb9d505cd0c673321_Poster.sol) as an example, the current parser returns the following nodes (among others):

```yaml
# ... many others

- !Choice
  - 0
  - !Named
    - NotStar
    - !Chars
      start: 594
      end: 595
- !Choice
  - 0
  - !Named
    - NotStar
    - !Chars
      start: 595
      end: 596
- !Choice
  - 0
  - !Named
    - NotStar
    - !Chars
      start: 596
      end: 597

# ... many others
```

Which are incorrect offsets, as trying to index into the string with these ranges result in:

```log
thread panicked at 'byte index 595 is not a char boundary; it is inside '█' (bytes 594..597)
```
