### ISSUE TITLE
Terminal choices don't take prefix into account

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#255]
For the current grammar on `main`:

```yaml
- name: OrderComparisonExpression
  config: { associativity: Left }
  sequence:
    - reference: Expression
    - choice:
        - terminal: "<"
        - terminal: ">"
        - terminal: "<="
        - terminal: ">="
    - reference: Expression
```

The expression `2 >= 1` would fail:

```log
Error: Expected '!' or '"' or ''' or '(' or '+' or '-' or '.' or '/' or '0' or '>' or '[' or 'f' or 'h' or 'n' or 'p' or 't' or 'u' or '~'.
   ╭─[1:4]
   │
 1 │ 2 >= 1
   ·    ┬  
   ·    ╰── Found '='.
───╯
```

If the grammar was re-ordered as below, it would parse correctly:

```yaml
- terminal: "<="
- terminal: ">="
- terminal: "<"
- terminal: ">"
```

Might be related to how we construct the lex trie in `codegen_parser` crate. Might also be related to #204
