### ISSUE TITLE
difference grammar expression doesn't filter subtrahend part

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#256]
For the current grammar on `main`:

```yaml
- name: Identifier
  kind: Token
  difference:
    minuend:
      reference: RawIdentifier
    subtrahend:
      reference: Keyword
```

This should reject the value `returns`, since it is a keyword. However, it is parsed as an identifier successfully.
