### ISSUE TITLE
Operator precedence detected incorrectly from grammar

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#271]
Looking at expression precedence:

https://github.com/NomicFoundation/slang/blob/c4cd942c434f3c0a64a1320ecf2e7d35805d5e41/crates/solidity/inputs/schema/topics/05-expressions/01-base-expressions.yml#L6-L24

The following rules are currently (on main branch) giving wrong results (example in https://github.com/NomicFoundation/slang/commit/527a9eb79eb211161a5cf9dcb9ceb13b92f24b5a):

* `foo` is parsed as a `FunctionCallExpression` successfully (without the parenthesis).
* `foo().bar` is failing to parse as a `MemberAccessExpression`

Looked at the grammar of both rules, and precedence looks correct. So I looked at the generated parser, and I do see a `unary_suffix_expression!()` macro used on rules that I didn't expect it to have it, like `FunctionCallExpression`. 
Looks like we are incorrectly detecting `OperatorModel` in `codegen_parser`. 

https://github.com/NomicFoundation/slang/blob/c4cd942c434f3c0a64a1320ecf2e7d35805d5e41/crates/solidity/outputs/rust/lib/src/generated/parse.rs#L1477-L1485

Do we need to specify `OperatorModel` and `Operator` on expressions directly (something like below)? or do we need to change our validation rules? thoughts?

```yml
# a specific expression type, instead of using choice + parserType, that allows only specific sub-expressions
# "operatorPrecedence" means that it will apply "folding" rules to return the inner-most expression, instead of a nested tree

- name: Expression
  kind: Rule
  operatorPrecedence:
    - referecene: AndExpression
    - referecene: IncrementExpression

# then child objects can specify its operator and associativity directly, more readable, and leaves nothing for guessing:

- name: AndExpression
  kind: Rule
  binaryOperator:
    associativity: Left
    left: FooExpression
    operator: "+"
    right: BarExpression

- name: IncrementExpression
  kind: Rule
  suffixOperator:
    expr: BazExpression
    operator: "+"
```
