### ISSUE TITLE
Should optional grammar nodes produce empty CST nodes?

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#282]
For this input:

```solidity
contract Sample {}
```

And this grammar:

```yml
- name: "ContractDefinition"
  kind: "Rule"
  unversioned:
    sequence:
      - name: "ContractAbstractSpecifier" # note the added name
        optional:
          terminal: "abstract"
      - terminal: "contract"
      - reference: "Identifier"
      - optional:
          reference: "InheritanceSpecifierList"
      - delimitedBy:
          open: "{"
          expression:
            zeroOrMore:
              reference: "ContractBodyElement"
          close: "}"
```

It produces the CST:

```yml
█ Rule(ContractDefinition) - (0..18)     │
├──► Token(Contract) - (0..8)            │ contract
├──► Token(Identifier) - (9..15)         │ Sample
└──█ Group - (16..18)                    │
   ├──► Token(OpenBrace) - (16..17)      │ {
   └──► Token(CloseBrace) - (17..18)     │ }
```

Should it produce a `ContractAbstractSpecifier` node with no children?

Same thing with `zeroOrMore` and `separatedBy` and `repeat(min=0)`, etc...

Additional context in https://github.com/NomicFoundation/slang/pull/178#discussion_r1004321743

> But if you choose to traverse the CST at some point, rather than visiting, this is very useful. It also allows for expected indices to be used in sequences when traversing.
