### ISSUE TITLE
expose operator semantics in grammar schema

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#310]
This is the failure I mentioned earlier. The current PR is a hack to make parsing succeed, while we investigate next.

Below is the precedence alternative. It currently fails with `A TerminalTrie with no entries should never have been constructed`. It assumes the existence of a binary operator, and fails as such. Might also be a part of our discussion on enforcing the explicit structure of each operator type (ternary/binary/unary) via YAML (an EBNF variant) instead detecting it later.

```yml
- name: "YulExpression"
  kind: "Rule"
  unversioned:
    parserType: "Precedence"
    choice:
      - reference: "YulFunctionCall"
      - reference: "YulPrimaryExpression"

- name: "YulFunctionCall"
  kind: "Rule"
  unversioned:
    sequence:
      - reference: "YulExpression"
      - delimitedBy:
          open: "("
          expression:
            optional:
              separatedBy:
                separator: ","
                expression:
                  reference: "YulExpression"
          close: ")"

- name: "YulPrimaryExpression"
  kind: "Rule"
  unversioned:
    choice:
      - reference: "YulIdentifierPath"
      - reference: "YulLiteral"
```

_Originally posted by @OmarTawfik in https://github.com/NomicFoundation/slang/pull/307#discussion_r1086546507_

**Comment by OmarTawfik** [comment]
I'm digging some more into the current parser codegen to see what other issues we have in the current schema.

**Comment by OmarTawfik** [comment]
@AntonyBlakey proposed the following form:

```yml
- name: "Expression"
  kind: "PrecedenceExpressionRule"
  versioned:
    0.4.11:
      # as below, but exponentiation is left associative
    0.6.0:
      operators:
        - binaryLeftOperator:
          name: "AssignmentExpression"
          choice:
            - terminal: "="
            - terminal: "|="
            - terminal: "^="
            - terminal: "&="
            - terminal: "<<="
            - terminal: ">>="
            - terminal: ">>>="
            - terminal: "+="
            - terminal: "-="
            - terminal: "*="
            - terminal: "/="
            - terminal: "%="
        - suffixOperator:
          name: "ConditionalExpression"
          sequence: # This subsequence forms the correct CST for the suffix expression parser
            - terminal: "?"
            - reference: "Expression"
            - terminal: ":"
            - reference: "Expression"
        - binaryLeftOperator:
          name: "OrExpression"
          terminal: "||"
        - binaryLeftOperator:
            name: "AndExpression"
            terminal: "&&"
        - binaryLeftOperator:
            name: "EqualityComparisonExpression"
            choice:
              - terminal: "=="
              - terminal: "!="
        - binaryLeftOperator:
            name: "OrderComparisonExpression"
            choice:
              - terminal: "<"
              - terminal: ">"
              - terminal: "<="
              - terminal: ">="
        - binaryLeftOperator:
            name: "BitOrExpression"
            terminal: "|"
        - binaryLeftOperator:
            name: "BitXOrExpression"
            terminal: "^"
        - binaryLeftOperator:
            name: "BitAndExpression"
            terminal: "&"
        - binaryLeftOperator:
            name: "ShiftExpression"
            choice:
              - terminal: "<<"
              - terminal: ">>"
              - terminal: ">>>"
        - binaryLeftOperator:
            name: "AddSubExpression"
            choice:
              - terminal: "+"
              - terminal: "-"
        - binaryLeftOperator:
            name: "MulDivModExpression"
            choice:
              - terminal: "*"
              - terminal: "/"
              - terminal: "%"
        - binaryRightOperator:
            name: "ExponentiationExpression"
            terminal: "**"
        - suffixOperator:
            name: "UnarySuffixExpression"
            choice:
              - terminal: "++"
              - terminal: "--"
        - prefixOperator:
            name: "UnaryPrefixExpression"
            choice:
              - terminal: "++"
              - terminal: "--"
              - terminal: "!"
              - terminal: "~"
              - terminal: "-"
        - suffixOperator:
            name: "FunctionCallExpression"
            sequence:
              - optional:
                  reference: "NamedArgumentList"
              - reference: "ArgumentList"
        - suffixOperator:
            name: "MemberAccessExpression"
            sequence:
              - terminal: "."
              - choice:
                  - reference: "Identifier"
                  - terminal: "address"
        - suffixOperator:
            name: "IndexAccessExpression"
            delimitedBy:
              open: "["
              expression:
                sequence:
                  - optional:
                      reference: "Expression"
                  - optional:
                      sequence:
                        - terminal: ":"
                        - optional:
                            reference: "Expression"
              close: "]"
      primaryExpressions: 
        - reference: "TypeExpression"
        - reference: "NewExpression"
        - reference: "ParenthesisExpression"
        - reference: "ElementaryType"
        - reference: "ArrayLiteral"
        - reference: "AsciiStringLiteral"
        - reference: "UnicodeStringLiteral"
        - reference: "HexStringLiteral"
        - reference: "NumericLiteral"
        - reference: "BooleanLiteral"
        - reference: "Identifier"
```
