### ISSUE TITLE
lookahead parser is not generated on rules

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#311]
@AntonyBlakey I tried something like the following, but parser codegen doesn't generate the lookahead:

```yaml
                    sequence:
                      - optional:
                          reference: "TypeName"
                          lookahead:
                            choice:
                              - reference: "DataLocation"
                              - reference: "Identifier"
                      - optional:
                          reference: "DataLocation"
                      - reference: "Identifier"
```

_Originally posted by @OmarTawfik in https://github.com/NomicFoundation/slang/pull/308#discussion_r1086555748_
