### ISSUE TITLE
not all named sub-expressions produce their own RuleKind

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#339]
I noticed an issue with the current parser codegen. Named sub-expressions no longer generate a `RuleKind`. To repro, adding `ContractName` to `ContractDefinition` below, doesn't add the new kind or change the CST. Test snapshots are unchanged as well.

**NOTE**: This also happens with `choice:` nodes, and possibly other types.

```yml
- name: "ContractDefinition"
  kind: "Rule"
  unversioned:
    sequence:
      - optional:
          terminal: "abstract"
      - terminal: "contract"
      - name: "ContractName"
        reference: "Identifier"
      - optional:
          reference: "InheritanceSpecifierList"
      - delimitedBy:
          open: "{"
          expression:
            zeroOrMore:
              reference: "ContractBodyElement"
          close: "}"
```
