### ISSUE TITLE
add separate keyword productions

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#505]
The way we specify keywords right now has many issues:

- Subtle bugs in earlier versions where keywords can/cannot be distinguished from identifiers because `Identifier` / `YulIdentifier` / `NotAnIdentifierInAnyVersion` / `NotAnIdentifierInSomeVersions` are not accurate/complete.
- The parser has to scan identifiers, and then scan again the union of all keywords to make sure it doesn't match, which is wasteful.

We can create a new `Keyword` production kind, where each keyword can specify the list of terminals it can match, and the list of identifiers it must not match. For example:

```yml
- name: "FixedBytesKeyword"
  kind: "Keyword"
  unversioned:
    terminals:
      - "bytes"
      - "bytes1"
      - "bytes2"
      - "bytes3"
    identifiers:
      - "Identifier"
      - "YulIdentifier"
```

For identifiers, we can scan the raw identifier, then do a quick string value comparison with all possible keywords it relates to (in each version) to make sure there is no match:

```rust
fn scan_identifier_0_6_0() {
  let identifier = scan_raw_identifier();
  match identifier {
    "keyword1" | "keyword2" | "keyword3" => {
      // list of keywords defined in 0.6.0
      return false;
    }
    _ => return true,
  };
}
```

For keywords, it will scan the same raw identifier, then match it with the list of terminals it has:

```rust
fn scan_bytes_keyword_0_4_11() {
  let identifier = scan_raw_identifier();
  match identifier {
    "bytes1" | "bytes2" | "bytes3" | ....... => {
      return true;
    }
    _ => return false,
  };
}
```

This structure allows us to have Solidity keywords referencing `Identifier`, and Yul keywords referencing `YulIdentifier`, and common ones like `IfKeyword` referencing both. Additionally, since keywords reference terminals (not the other way around), they can be versioned as usual.

This will remove the need for `trailingContext` and `difference`, as we can replace both with existing expressions.
