### ISSUE TITLE
slash fails to parse as a user defined operator

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#519]
Adding a `UsingDirective` test with contents:

```solidity
using {div as /} for Int;
```

would produce the following error, instead of succeeding:

```yaml
Source: >
  1  │ using {div as /} for Int global;                                                 │ 0..32

Errors: # 1 total
  - >
    Error: Expected Ampersand or Asterisk or BangEqual or Bar or Caret or EqualEqual or GreaterThan or GreaterThanEqual or LessThan or LessThanEqual or Minus or Percent or Plus or Slash or Tilde.
       ╭─[crates/solidity/testing/snapshots/cst_output/UsingDirective/user_defined_operator/input.sol:1:14]
       │
     1 │ using {div as /} for Int global;
       │              ─────────┬─────────  
       │                       ╰─────────── Error occurred here.
    ───╯

Tree:
  - UsingDirective (Rule): # 0..32 "using {div as /} for Int global;"
      - UsingKeyword (Token): "using" # 0..5
      - OpenBrace (Token): "{" # 6..7
      - IdentifierPath (Rule): # 7..10 "div"
          - Identifier (Token): "div" # 7..10
      - AsKeyword (Token): "as" # 11..13
      - SKIPPED (Token): " /} for Int global;" # 13..32
```
