### ISSUE TITLE
AddressType wrongly accepts just `payable` state mutability as the whole type

### ISSUE THREAD

**Issue by Xanewok** [NomicFoundation/slang#654]
YAML spec
```yaml
- name: "AddressType"
  kind: "Parser"
  unversioned:
    choice:
      - sequence:
          - reference: "AddressKeyword"
          - optional:
              reference: "PayableKeyword"
      - reference: "PayableKeyword"
```

DSL v1
```rust
parser AddressType = ((AddressKeyword (PayableKeyword ?)) | PayableKeyword) ;
```

DSL v2
```rust
Struct(
    name = AddressType,
    fields = (
        address_keyword = Required(Terminal([AddressKeyword])),
        payable_keyword = Optional(kind = Terminal([PayableKeyword]))
    )
)
```
but `ElementaryType` accepts `PayableKeyword` alongside `AddressType`.

The address type should be `address (payable)`. There is also `payable(<address>)` conversion expression but that should be handled separately, as `payable` on its own is not an elementary type.
